### ISSUE TITLE
Can't get this working

### ISSUE THREAD

**Issue by elucidsoft** [ysugimoto/cloudflare-worker-lambda-gateway#1]
I can't for the life of me get this working, I always get back the response 'Unable to determine service/operation name to be authorized'.  Any idea why?

I am using the code in this repo, the only thing I changed was region to us-east-1, and the API key.  The user has AWSLambdaExecute and AWSLambdaRole.  I've spent several hours trying everything.  I am not sure why this won't work.

The arn for my lambda is arn:aws:lambda:us-east-1:375780317710:function:test2, I pass in test2 and the variable 'fn' has a value of /test2 so everything looks fine.  I am at a loss, can you please help?

**Comment by ysugimoto** [comment]
@elucidsoft Hi,

I just found problem that a request url will have double slash path like `https://lambda.
[region].amazonaws.com//2015-03-31/functions/[function name]/invocations/`, and it will be failed on AWS. I fixed it and works fine in my function calling.

Could you try again with latest branch?
